### ISSUE TITLE
MaterialComboBox issue with multiple selection

### ISSUE THREAD

**Issue by tbenbrahim** [GwtMaterialDesign/gwt-material-addins#197]
Getting a class cast exception when calling `getSelectedValues()`.
A console.log of the listbox shows the values are not set in `setValues`.

All I can offer at this point is a failing test case:
- https://github.com/tbenbrahim/gwt-material-addins/blob/combobox-multiselect/src/test/java/gwt/material/design/addins/client/MaterialComboBoxTest.java#L194
- https://github.com/tbenbrahim/gwt-material-addins/blob/combobox-multiselect/src/test/java/gwt/material/design/addins/client/dto/SampleModel.java

**Comment by kevzlou7979** [comment]
It seems the issue on the usage of ```value.toString()``` instead of ```keyfactory.generateKey(value)```. I got a fixed for it on 2.0-SNAPSHOT https://github.com/GwtMaterialDesign/gwt-material-addins/commit/74a7618b970589ad4d3ad1ec23c9c12f7b94f2c7. Also last thing, the Test seems to have issue on casting ```Object[]``` into JUnit Test. Everything works fine on demo test.

See below the demo:
https://github.com/GwtMaterialDesign/gwt-material-issue-test/tree/addins_%23197
