### ISSUE TITLE
Restore single package for all widgets

### ISSUE THREAD

**Issue by 8vale8** [GwtMaterialDesign/gwt-material-addins#42]
I would suggest reverting the package reorganization of components:
referencing multiple components in a single ui binder file has become unmaintenaible because each component requires its own urn:import.

**Comment by BenDol** [comment]
Hmm this is one of the downsides to uibinder with the standard java packaging structure. I tend to agree that its a big annoying, I wonder if we could just move them back to one package and keep the resources inside their own packages, since that was the main benefit for the package restructure.

**Comment by francescoforesti** [comment]
I don't know if GWT has a convention for package organization (apart from the client-server-shared thing), but if there is one I'd suggest to adopt it. As a last resort, wouldn't it be better to adopt the same organization of the GWT library itself? IMHO users would expect consistency within the GWT environment (well, I do).

**Comment by BenDol** [comment]
It would be great if the uibinder supported `package.*` imports.

**Comment by kevzlou7979** [comment]
Please read the gitter channel, gilberto posted a single import of addins
ysing the new resource reorg.

**Comment by BenDol** [comment]
That is good, forgot you could do that :+1: it gets a little long sometimes but it works.

**Comment by kevzlou7979** [comment]
Yeah thats it, i will close now this issue. I hope @8vale8 is clear now. I will also add a note for the showcase site specially the codesnippets

**Comment by masini** [comment]
I did some tests downloading gwt-material (release_15) and gwt-material-addins (master), and is not annoying, is a real disaster having widgets in separate packages.

First of all my IDE (Idea 2006.1.1), which has the better UI Binder editor in the market, is unable to autocomplete the tag and the tag with namespace.

Doing this will mean that I need to:
1) Add the namespace in the uri section
2) Autocomplete a single tag
for every single tag, in a word, it doesn’t work !!!

Another annoying effect of a per-package organization is that in case of a new refactor I’ll need to change every tag instead of a single URI import.

Please rollback this refactor.

Thanks.

**Comment by kevzlou7979** [comment]
@masini Yeah I know how it goes, But we have decided to use this package declaration as GWT Bootstrap does to support lazy loading because if we dont implement it, it may have a slow performance on our GWT Apps specially if we will implement so many addins (All Javascript/ CSS resources will be loaded even though you just declrate 1 or 2 addin - It will import all). 

Next thing about the Autocomplete Tag, We will soon provide the codesnippet in the showcase app for copy pasting. Also as @BenDol said you can do single import of widgets then just add the 
```
<ma:bubble.MaterialBubble />
<ma.cutout:MaterialCutOut/>

```

**Comment by 8vale8** [comment]
Thanks for your replies.

Yes it works that way... still it feels like a "trick" to make things work, when I press Ctrl+Space the IDE does not make suggestions anymore so I am forced to look into the source code to see what package contains the widget I want to use.
I agree that lazy loading of resources is fundamental but it could be done even with the previous package organization: since each widget loads its own resources and has its bundle, the resources can be anywhere independently from the widget itself.

I won't insist anymore I swear :) 
Just think that from a user's point of view it is a big pity that such a great library has this penalty in terms of usability and code cleanup that could be avoided.

**Comment by BenDol** [comment]
From development perspective having the libraries organised like this is really useful since they are majority of the time an external library. So keeping the classes packaged according helps to avoid confusion. I think if the IDE isn't autocompleting with this method it needs to be raised with the IDE developers since it is a valid method for importing in the uibinder.
