### ISSUE TITLE
Static js injection

### ISSUE THREAD

**Issue by paulux84** [GwtMaterialDesign/gwt-material-addins#47]
Using static block injection in widget like for example MaterialTimePicker cause error if widget is attached trough UiBinder.
I get that corresponding js method not exist. The problem is that the js method is called without knowing if js library is loaded

**Comment by paulux84** [comment]
Why MaterialResourceInjector inject library deffered? This cause the problem

**Comment by BenDol** [comment]
I think there are issues with the static importing of resources. There are many cases where it attempts to inject to early or too late. I think there needs to be an injection queue for post the EntryPoint.

**Comment by gilberto-torrezan** [comment]
> Why MaterialResourceInjector inject library deffered? This cause the problem

That's to enable the GWT code splitter to download the needed code when when necessary, avoiding a large download at the startup time of the application (which is terrible for the UX). Adding everything on the EntryPoint causes a large download before anything can be rendered on the screen (unless you create a dynamic server-rendered page just for that).

If you don't use the code splitter, or a framework that does the splitting for you, you should consider using one.

About the problem, do you have a sample code to share where the problem occurs? I'm using MaterialTimePicker (and other widgets with same approach) through UiBinder without problems.

**Comment by kevzlou7979** [comment]
@paulux84 I have tested it on separate project about the addins and so far so good, @gilberto-torrezan  Thanks for your response.

**Comment by paulux84** [comment]
The problem sometimes occurs and sometimes not...is clearly a load time problem because I get for example jquery...lolliclock not exist. Not simple to recreate in little project, but I'm sure...the bug exist and my log file confirm that. 
@gilberto-torrezan GWT.runAsync is the way to obtain code splitting. DeferredCommand have the only role of non blocking client op or schedule command.

**Comment by gilberto-torrezan** [comment]
Yes, indeed the GWT.runAsync is the command that allows the code splitter to know the boundary of what can be split... but what ends in which code fragment depends on the structure of the code.

If you load everything on the module load, every JS file will be at the first fragment of the code. Let's say you split the code based on Views/Presenters, and the first view of your application is a login screen, where you don't use a MaterialTimePicker at all. If you load the JS at the module load, the JS file will be at the very first code fragment of your application (which doesn't need the code for MaterialTimePicker), slowing down the start of the app for no reason - which is bad for UX.

Or course, talking about a single JS file data is no big deal, but when you load several JS files from several different components, that can create a problem.

So, loading the JS file on the static "constructor" of the class is good for the code splitter (it doesn't guarantee that code is split, but when you use GWT.runAsync, directly or indirectly, the JS file data will be only on the fragment where the widget is actually used).

How are you loading the JQuery? By using a `GwtMaterial*WithJQuery` module or by importing it by yourself? Maybe the problem you're having is not related to the MaterialTimePicker itself, but with JQuery.

**Comment by paulux84** [comment]
@gilberto-torrezan  i get "lolliclock" not exist...not jquery...and this error isn't only on MaterialPicker, but in all widget with the import on the static constructor. if i force the load of js with a mock instantiation of the widget...all work. Why? Because the problem is that some method was called before initialization of js files. Call this methods must be a callback to the js load.

**Comment by gilberto-torrezan** [comment]
@paulux84 I need to understand what's different on your setup, because:

1 - I have 3 projects running with GWT Material, all with the latest version (1.5), and all using several addins, and none of them presented the error you're speaking (tested on Chrome, Firefox and Edge, clearing the cache and running on private/incognito tabs);
2 - The GWT Material demo itself, which uses, well, all addins, also doesn't show the error.

So I can imagine some scenarios:

1 - The way you import GWT Material is different from those 4 applications (I ask again, which `GwtMaterial*` module are you using?);
2 - You're using some framework to handle navigation/presenters/injection that is different from those applications and that is creating problems;
3 - There's another silent error happening on the application that causes the loading of JS to not complete successfully;
4 - There's some conflict between scripts loaded externally to GWT Material in your page.

Without clear information on how to reproduce the bug, we can only speculate. Blaming the way the scripts are loaded, in my opinion, is a little premature, considering that an error on that mechanism should be easy to reproduce on any environment.

Questions I'd appreciate you could answer:

Does your app have a public URL we can access? Can you share which frameworks are you using, and how are you loading the GWT Material module? Can you provide a SSCCE where this bug occurs? In your environment, does the GWT Material Demo loads correctly?

Thanks.

**Comment by paulux84** [comment]
I help you as soon as possible. 
I wish next week to do something useful. 
Bye
Il 18/Apr/2016 20:08, Gilberto Torrezan <notifications@github.com> ha scritto:@paulux84 I need to understand what's different on your setup, because:

1 - I have 3 projects running with GWT Material, all with the latest version (1.5), and all using several addins, and none of them presented the error you're speaking (tested on Chrome, Firefox and Edge, clearing the cache and running on private/incognito tabs);
2 - The GWT Material demo itself, which uses, well, all addins, also doesn't show the error.

So I can imagine some scenarios:

1 - The way you import GWT Material is different from those 4 applications (I ask again, which GwtMaterial* module are you using?);
2 - You're using some framework to handle navigation/presenters/injection that is different from those applications and that is creating problems;
3 - There's another silent error happening on the application that causes the loading of JS to not complete successfully;
4 - There's some conflict between scripts loaded externally to GWT Material in your page.

Without clear information on how to reproduce the bug, we can only speculate. Blaming the way the scripts are loaded, in my opinion, is a little premature, considering that an error on that mechanism should be easy to reproduce on any environment.

Questions I'd appreciate you could answer:

Does your app have a public URL we can access? Can you share which frameworks are you using, and how are you loading the GWT Material module? Can you provide a SSCCE where this bug occurs? In your environment, does the GWT Material Demo loads correctly?

Thanks.

**Comment by kevzlou7979** [comment]
@paulux84 we can use Team Viewer for realtime confirmation.

**Comment by mvanrobaeys** [comment]
I guess issue 60 is a dupe from this one.  
I have adapted the demo project to show this issue: https://github.com/mvanrobaeys/gwt-material-demo

Change MaterialRichEditor with the MaterialPicker for the lolliclock issue

**Comment by BenDol** [comment]
@mvanrobaeys thanks for that, seems when the code is executed from the EntryPoint it hasn't initiated the static block with the injection. Needs to be resolved ASAP.

**Comment by BenDol** [comment]
Resolved https://github.com/GwtMaterialDesign/gwt-material-addins/commit/01841293041fc7107e4e09ccff1d9318b5a2d6a1

**Comment by vegegoku** [comment]
this issue also happens when you use addins in a test case
i use a MaterialSideProfile in my view definition, and i have a test case that uses GwtMockitoTestRunner
when ever i run the test case i end up with error in injecting the css

```
java.lang.ExceptionInInitializerError
	at gwt.material.design.client.MaterialDesignBase.injectCss(MaterialDesignBase.java:93)
	at gwt.material.design.addins.client.sideprofile.MaterialSideProfile.<clinit>(MaterialSideProfile.java:67)
	at com.sample.using.addins.with.gwtmockito.UserInfoClientModuleTest.lambda$setUp$0(UserInfoClientModuleTest.java:32)
	at com.google.gwtmockito.GwtMockito.getFakeFromProviderMap(GwtMockito.java:268)
	at com.google.gwtmockito.GwtMockito.access$300(GwtMockito.java:94)
	at com.google.gwtmockito.GwtMockito$Bridge.create(GwtMockito.java:311)
	at com.google.gwt.core.shared.GWT.createImpl(GWT.java:83)
	at com.google.gwt.core.client.GWT.create(GWT.java:86)
	at com.google.gwtmockito.fakes.FakeUiBinderProvider$1.invoke(FakeUiBinderProvider.java:64)
```

knowing that it is still working if i compile and run with super dev mode.
but yet i need my test cases to pass.
