### ISSUE TITLE
MaterialAutoComplete type=TEXT throws an exception in demo

### ISSUE THREAD

**Issue by ratuka** [GwtMaterialDesign/gwt-material-addins#61]
http://gwtmaterialdesign.github.io/gwt-material-demo/#!autocomplete

scroll to the TYPE TEXT example, click on the textbox, than type L, select the first suggestion, than see the console for the error

![chrome](https://cloud.githubusercontent.com/assets/2168212/14861218/8f8714e8-0cac-11e6-8cfb-7bff42e7c389.png)
![ff](https://cloud.githubusercontent.com/assets/2168212/14861219/8faa4328-0cac-11e6-867d-9c3cbc5235d7.png)
![ie11](https://cloud.githubusercontent.com/assets/2168212/14861220/8faa51f6-0cac-11e6-8bd5-91d1614be642.png)

**Comment by kevzlou7979** [comment]
@ratuka Thanks I confirmed the bug exists

**Comment by BenDol** [comment]
Has this been resolved?

**Comment by ratuka** [comment]
Unfortunately not. Even in the latest 1.6.0 snapshot it throws "uncaught exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: This widget's parent does not implement HasWidgets"

**Comment by ingosch** [comment]
I've traced this error down but I'm not sure how to fix it.
MaterialAutoComplete uses GWT SuggestBox and injects it's own TextBox into it. SuggestBox doesn't implement HasWidgets interface, so the TextBox can't be removed from it later.
But that's what happens when an item is added in "TEXT"-Mode (MaterialAutoComplete Line 353). MaterialAutoComplete tries to add the Box to a ListItem what causes the Box's "removeFromParent" function (of Widget class) to be called.
This Exception is also thrown when setting the SuggestOracle a second time, cause the TextBox is only instantiated once as an instance variable and reused while the SuggestBox is created new.

**Comment by BenDol** [comment]
The TextBox shouldn't be reattaching itself in the display item. Will submit the fix tonight.

**Comment by kevzlou7979** [comment]
@BenDol Nice one
