### ISSUE TITLE
Addins not rendering

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material-addins#91]
Components from xmlns:ma="urn:import:gwt.material.design.addins.client.autocomplete" fail to render. Nothing is added in the DOM. I see no exception anywhere.
Other components (e.g. from xmlns:m="urn:import:gwt.material.design.client.ui") render just fine.

I tried both variations <ma:MaterialAutoComplete/> and <ma:autocomplete.MaterialAutoComplete/> (with NS declaration updatet accordingly)
Also I tested both SuperDevMode and compiled/deployed version.

Issue is also mentioned here on [Stackoverflow.com](http://stackoverflow.com/questions/37169212/gwt-material-design-addin) and [Google Groups](https://groups.google.com/forum/#!topic/google-web-toolkit/t_x6Gv0OWrI). (Reported by the same person.)

My module XML:
```
<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder"
	xmlns:m="urn:import:gwt.material.design.client.ui"
	xmlns:ma="urn:import:gwt.material.design.addins.client.autocomplete">

	<m:MaterialPanel>
		<m:MaterialLabel text="Hello" />
		<ma:MaterialAutoComplete placeholder="Contacts" ui:field="autocomplete"/>
	</m:MaterialPanel>
</ui:UiBinder>
```
GwtMaterialDesign 1.5.1, GwtMaterialAddins 1.5.1 and GWT 2.8.0-beta1

**Comment by kevzlou7979** [comment]
When i see yur code, its incomplete why? Because theres no data on it. You
need to populate it using Java please make sure to refer to documentation
On Jun 19, 2016 5:31 PM, "jzaruba" <notifications@github.com> wrote:

Components from
xmlns:ma="urn:import:gwt.material.design.addins.client.autocomplete" fail
to render. Nothing is added in the DOM. Other components (e.g. from
xmlns:m="urn:import:gwt.material.design.client.ui" render just fine.

I tried both variations ma:MaterialAutoComplete/ and
ma:autocomplete.MaterialAutoComplete/ (with NS declaration updatet
accordingly)
Also I tested both SuperDevMode and compiled/deployed version.

Issue is also mentioned here on Stackoverflow.com
<http://stackoverflow.com/questions/37169212/gwt-material-design-addin>
and Google
Groups
<https://groups.google.com/forum/#!topic/google-web-toolkit/t_x6Gv0OWrI>.
(Reported by the same person.)

My module XML:

<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder"
    xmlns:m="urn:import:gwt.material.design.client.ui"
    xmlns:ma="urn:import:gwt.material.design.addins.client.autocomplete">

    <m:MaterialPanel>
        <m:MaterialLabel text="Hello" />
        <ma:MaterialAutoComplete placeholder="Contacts"
ui:field="autocomplete"/>
    </m:MaterialPanel>
</ui:UiBinder>

GwtMaterialDesign 1.5.1, GwtMaterialAddins 1.5.1 and GWT 2.8.0-beta1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GwtMaterialDesign/gwt-material-addins/issues/91>, or mute
the thread
<https://github.com/notifications/unsubscribe/AC_iF31MrKjvoXdovD4KXCOigVWdmZCfks5qNQyNgaJpZM4I5INe>
.

**Comment by jzaruba** [comment]
Oh, I expected to get empty autocomplete box or maybe an exception. Thank you, sir! Will try!
